TaskProject/urls.py
from django.urls import path

from TaskProject.views import (TaskListView,
                               TagListView,
                               TaskCreateView,
                               TagCreateView,
                               TaskUpdateView,
                               TagUpdateView,
                               TaskDeleteView,
                               TagDeleteView,
                               TaskChangeStatusView
                               )

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),
    path("change_status/<int:pk>", TaskChangeStatusView.as_view(), name='task_change_status'),
    ]

app_name = "TaskProject"

Task_Practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("TaskProject.urls", namespace="TaskProject")),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TaskProject/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]


class Task(models.Model):
    content = models.CharField(max_length=63, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["created_at", "is_done"]

    def __str__(self):
        return f"Task: {self.content} ({self.tags})"


TaskProject/forms.py
from django import forms

from TaskProject.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

TaskProject/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from TaskProject.forms import TaskForm, TagForm
from TaskProject.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "TaskProject/task_list.html"
    paginate_by = 5
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "TaskProject/task_form.html"
    success_url = reverse_lazy("TaskProject:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "TaskProject/task_form.html"
    success_url = reverse_lazy("TaskProject:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    template_name = "TaskProject/task_confirm_delete.html"
    success_url = reverse_lazy("TaskProject:task-list")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "TaskProject/tag_list.html"
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "TaskProject/tag_form.html"
    success_url = reverse_lazy("TaskProject:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "TaskProject/tag_form.html"
    success_url = reverse_lazy("TaskProject:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    template_name = "TaskProject/tag_confirm_delete.html"
    success_url = reverse_lazy("TaskProject:tag-list")


class TaskChangeStatusView(View):
    def post(self, request, pk):
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()

        return redirect(reverse_lazy('TaskProject:task-list'), permanent=True)

    def get(self, request):
        return redirect(reverse_lazy('TaskProject:task-list'), permanent=True)

TaskProject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/TaskProject/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete tag</h1>


  <p>Are you sure you want to delete the tag {{ tag }}?</p>

  <form action="" method="post">
  {% csrf_token %}
      <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/TaskProject/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" value="submit">
  </form>
{% endblock %}

templates/TaskProject/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Tags</h1>
      <button class="btn btn-primary float-end me-3 mb-3">
        <a role="button" class="text-white" href="{% url 'TaskProject:tag-create'%}">
          Add
        </a>
      </button>


    {% if tag_list %}
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            {% for tag in tag_list %}
            <tr>
              <td>
                {{ tag.name }}
              </td>
              <td>
                <a href="{% url 'TaskProject:tag-update' pk=tag.id %}" class="btn btn-info link-to-page">
                  Update
                </a>
              </td>
              <td>
                <a href="{% url 'TaskProject:tag-delete' pk=tag.id %}" class="btn btn-danger link-to-page">
                  Delete
                </a>
              </td>
            </tr>
            {% endfor %}

        </table>

    {% else %}
        <p>There are no tasks for now!</p>
    {% endif %}

{% endblock %}

templates/TaskProject/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete task</h1>

    <p>Are you sure you want to delete the task {{ task }}?</p>

    <form action="" method="post">
    {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-danger">
    </form>
{% endblock %}

templates/TaskProject/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post">
    {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit" value="submit">
  </form>
{% endblock %}

templates/TaskProject/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Task list</h1>
    <button style="float: right; bottom: 50px; position: relative" class="btn btn-primary"
            type="submit"
            value="submit">
        <a role="button" style="color: white"
           href="{% url 'TaskProject:task-create' %}">Add task</a>
    </button>
    <br>

    {% if task_list %}
        {% for task in task_list %}
            <br>
            <div class="form-group">
                <b>{{ task.content }}</b>


                {% if task.is_done %}
                    <b><span class="done">Done</span></b>
                    <form method="post" action="{% url 'TaskProject:task_change_status' pk=task.id %}">
                        {% csrf_token %}

                        <button style="float: right" type="submit" class="btn btn-blurred">
                            Undo
                        </button>

                    </form>

                {% else %}
                    <b><span class="not-done">Not done</span></b>

                    <form method="post" action="{% url 'TaskProject:task_change_status' pk=task.id %}">
                        {% csrf_token %}
                        <button style="float: right" type="submit" class="btn btn-success">
                            Complete
                        </button>
                    </form>

                {% endif %}

            </div>
            <div class="form-group">
                Created: {{ task.created_at }} {% if task.deadline %}
                <span class="text-deadline">Deadline: {{ task.deadline }}</span>
            {% endif %}
            </div>
            <div class="form-group">
                <b><span class="text-tag"> Tags:
                    {% for tag in task.tags.all %}
                        {{ tag.name }}
                    {% endfor %}
                </span></b>


                <a href="{% url 'TaskProject:task-update' pk=task.id %}">Update</a>
                <a href="{% url 'TaskProject:task-delete' pk=task.id %}">Delete</a>
            </div>
        {% endfor %}

    {% else %}
        <p>There are no tasks for now!</p>
    {% endif %}



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Task list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>

<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'TaskProject:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'TaskProject:tag-list' %}">Tags</a></li>
</ul>